package com.pearadmin.boke.entry;

import java.sql.Timestamp;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;

/**
 * bokes
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
@Data
public class Bokes implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6860943679883810999L;

    /* This code was generated by TableGo tools, mark 1 begin. */
    @TableId(value = "boke_id",type = IdType.AUTO)
//    @TableField(exist = false)
    private Integer bokeId;

    private String title;

    private String bokeCont;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp createTime;

    private Integer cateId;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp updateTime;

    private Long userId;

    private Integer likeNum;

    private Integer replyNum;

    private Integer lookNum;

    private String labelId;
    
    private String createDate;
    
    private String introduction;
    
    private Integer editorType;
    
    private Integer priPub;
    
    private String mdContent;
    
    @TableField(exist = false)
    private String signature;
    
//    0未压缩1压缩
    private Integer bokeZip;
    
    private Integer shareNum;
    
    private Integer deleteState;
    private Integer bokeExamine;
    
    private String labelNames;

    @TableField(exist = false)
    private Integer lId;

}