package com.pearadmin.boke.entry;

import java.util.List;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;

import lombok.Data;

/**
 * 评论(comments)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
@Data
public class Comments implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3925726664304864906L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @TableId(value = "comm_id",type = IdType.AUTO)
    private Integer commId;

    private String commTont;

//    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String commTime;

    private Integer commLikeNum;

    private Long userId;

    private Integer bokeId;

    private String userIp;
    
//    0未审核1审核不通过
    private Integer commVerify;
    
    @TableField(exist = false)
    private String avatar;

    /* This code was generated by TableGo tools, mark 1 end. */
    
    @TableField(exist = false)
    private String username;
    
//    回复列表
    @TableField(exist = false)
    private List<Replys> replys;

    /* This code was generated by TableGo tools, mark 3 end. */
}