package com.pearadmin.boke.entry;

import java.sql.Timestamp;

import com.baomidou.mybatisplus.annotation.TableId;
import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;

/**
 * 标签(labels)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
@Data
public class Labels implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6969043620598826403L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @TableId
    private Integer labelId;

    private String labelName;

    private String description;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp createTime;
    
    private Integer deleteState;

}