package com.pearadmin.boke.entry;

import com.baomidou.mybatisplus.annotation.TableId;

import java.sql.Timestamp;
import java.util.Date;

import lombok.Data;

/**
 * 用户表(users)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
@Data
public class Users implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5141948197349152280L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @TableId
    private Integer userId;

    private String userName;

    private String password;

    private String loginIp;

    private String userEmail;

    private String userFace;

    private Timestamp registerTime;

    private Timestamp loginTime;

    private String registerIp;

    private Date birthday;

    private Integer userAge;

    private String phone;
    
    private String signature;
//    1不绑定2绑定
    private Integer emailBind;
    
    private Integer phoneBind;
    
    private String wxUrl;
    private String qqUrl;
    private String csdnUrl;
    private String giteeUrl;
    private String githubUrl;
    private String weiboUrl;
    private String biliUrl;
    
    private int userState;
    
    public Users() {
    }

    public Users(Integer userId, String userName) {
        this.userId = userId;
        this.userName = userName;
    }
}